/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./components/views/AboutView.vue')['default']
    AuthNavbar: typeof import('./components/molecules/AuthNavbar.vue')['default']
    BookCard: typeof import('./components/molecules/BookCard.vue')['default']
    BookListItem: typeof import('./components/molecules/BookListItem.vue')['default']
    BooksPagination: typeof import('./components/atoms/BooksPagination.vue')['default']
    BooksView: typeof import('./components/views/books/BooksView.vue')['default']
    BookView: typeof import('./components/views/books/BookView.vue')['default']
    ButtonForm: typeof import('./components/atoms/ButtonForm.vue')['default']
    ButtonGroup: typeof import('./components/atoms/ButtonGroup.vue')['default']
    FieldMessage: typeof import('./components/atoms/FieldMessage.vue')['default']
    HeroView: typeof import('./components/views/HeroView.vue')['default']
    HomeView: typeof import('./components/views/HomeView.vue')['default']
    InputField: typeof import('./components/atoms/InputField.vue')['default']
    LoginForm: typeof import('./components/molecules/LoginForm.vue')['default']
    LoginView: typeof import('./components/views/auth/LoginView.vue')['default']
    PublicNavbar: typeof import('./components/molecules/PublicNavbar.vue')['default']
    RegisterView: typeof import('./components/views/auth/RegisterView.vue')['default']
    RegistrationForm: typeof import('./components/molecules/RegistrationForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
